name: ci-cd
on: workflow_dispatch # TODO: Change to push 
run-name: Deploy with new code

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.EC2_IP  }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /ubuntu/deploy-kit
            git pull
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml down
            bun run start-prod
      
      - name: Complete
        run: echo "CICD complete"


